# Generated by Django 3.2.25 on 2025-07-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('royal', 'Royal Oda'), ('exclusive', 'Exclusive Oda'), ('luxury', 'Luxury Oda'), ('executive', 'Executive Oda'), ('superior', 'Superior Oda'), ('turkish_hamam_cave', 'Türk Hamamlı Mağara Oda')], max_length=20),
        ),
    ]
