# Generated by Django 4.2.7 on 2025-11-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_room_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_tr",
                    models.CharField(max_length=100, verbose_name="Oda Adı (TR)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Room Name (EN)"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=100, verbose_name="Zimmer Name (DE)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la Chambre (FR)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Habitación (ES)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, verbose_name="Название номера (RU)"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="اسم الغرفة (AR)"),
                ),
                ("description_tr", models.TextField(verbose_name="Açıklama (TR)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_de", models.TextField(verbose_name="Beschreibung (DE)")),
                ("description_fr", models.TextField(verbose_name="Description (FR)")),
                ("description_es", models.TextField(verbose_name="Descripción (ES)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_ar", models.TextField(verbose_name="الوصف (AR)")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Oda Türü",
                "verbose_name_plural": "Oda Türleri",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rooms/", verbose_name="Resim")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Resim Başlığı"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Resim gösterilemediğinde gösterilecek text",
                        max_length=200,
                        verbose_name="Alt Text (SEO)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Ana sayfa'da bu resmi göster",
                        verbose_name="Ana Sayfa Thumbnail",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mainapp.roomcategory",
                        verbose_name="Oda Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Resimi",
                "verbose_name_plural": "Oda Resimleri",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fa-bed", "Yatak"),
                            ("fa-bath", "Banyo"),
                            ("fa-tv", "Televizyon"),
                            ("fa-wifi", "Wi-Fi"),
                            ("fa-mug-hot", "Mini Bar"),
                            ("fa-snowflake", "Klima"),
                            ("fa-couch", "Oturma Alanı"),
                            ("fa-door-open", "Teras"),
                            ("fa-water", "Jacuzzi"),
                            ("fa-fan", "Soğutma"),
                            ("fa-hair-dryer", "Saç Kurutma Makinesi"),
                            ("fa-key", "Kasa"),
                            ("fa-phone", "Telefon"),
                            ("fa-utensils", "Mini Mutfak"),
                            ("fa-briefcase", "Çalışma Alanı"),
                        ],
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "text_tr",
                    models.CharField(max_length=200, verbose_name="Özellik (TR)"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=200, verbose_name="Feature (EN)"),
                ),
                (
                    "text_de",
                    models.CharField(max_length=200, verbose_name="Merkmal (DE)"),
                ),
                (
                    "text_fr",
                    models.CharField(
                        max_length=200, verbose_name="Caractéristique (FR)"
                    ),
                ),
                (
                    "text_es",
                    models.CharField(
                        max_length=200, verbose_name="Característica (ES)"
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=200, verbose_name="Особенность (RU)"),
                ),
                (
                    "text_ar",
                    models.CharField(max_length=200, verbose_name="الميزة (AR)"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "room_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="mainapp.roomcategory",
                        verbose_name="Oda Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Özelliği",
                "verbose_name_plural": "Oda Özellikleri",
                "ordering": ["display_order"],
            },
        ),
    ]
