# Generated by Django 4.2.7 on 2025-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_roomcategory_roomimage_roomfeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(max_length=200, verbose_name="Başlık (TR)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Überschrift (DE)"),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (FR)"),
                ),
                (
                    "title_es",
                    models.CharField(max_length=200, verbose_name="Título (ES)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="العنوان (AR)"),
                ),
                ("content_tr", models.TextField(verbose_name="İçerik (TR)")),
                ("content_en", models.TextField(verbose_name="Content (EN)")),
                ("content_de", models.TextField(verbose_name="Inhalt (DE)")),
                ("content_fr", models.TextField(verbose_name="Contenu (FR)")),
                ("content_es", models.TextField(verbose_name="Contenido (ES)")),
                ("content_ru", models.TextField(verbose_name="Содержание (RU)")),
                ("content_ar", models.TextField(verbose_name="المحتوى (AR)")),
                ("image", models.ImageField(upload_to="about/", verbose_name="Resim")),
                (
                    "image_position",
                    models.CharField(
                        choices=[("left", "Sol"), ("right", "Sağ")],
                        default="left",
                        max_length=10,
                        verbose_name="Resim Pozisyonu",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hakkımızda Bölümü",
                "verbose_name_plural": "Hakkımızda Bölümleri",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="GoogleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Google Review ID"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="Yazar Adı"),
                ),
                (
                    "author_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Yazar URL"
                    ),
                ),
                (
                    "profile_photo_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Profil Fotoğrafı"
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Puan (1-5)")),
                ("text", models.TextField(verbose_name="Yorum")),
                ("published_at", models.DateTimeField(verbose_name="Yayın Tarihi")),
                (
                    "language",
                    models.CharField(default="tr", max_length=10, verbose_name="Dil"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Senkronize Tarihi"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Ana sayfada göster"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
            ],
            options={
                "verbose_name": "Google Yorum",
                "verbose_name_plural": "Google Yorumlar",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="HomePageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("slider", "Ana Sayfa Slider (Hero)"),
                            ("about", "Hakkımızda Bölümü"),
                            ("experiences", "Deneyimler Bölümü"),
                            ("activities", "Aktiviteler Bölümü"),
                        ],
                        max_length=50,
                        verbose_name="Bölüm",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "image",
                    models.ImageField(upload_to="homepage/", verbose_name="Resim"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Alt Yazı"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ana Sayfa Resimi",
                "verbose_name_plural": "Ana Sayfa Resimleri",
                "ordering": ["section", "display_order"],
            },
        ),
    ]
