# Generated by Django 4.2.7 on 2025-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_aboutsection_googlereview_homepageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlereview",
            name="review_photos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Yorumla birlikte paylaşılan fotoğraflar",
                verbose_name="Yorum Fotoğrafları",
            ),
        ),
    ]
